version: '3.6'
services:
  yolov3:
    image: "vaneesh/zed_yolo_final:v9.1_calibration"
    ports:
      - "5432:22"
    privileged: true
    environment:
      - DISPLAY=
      - QT_X11_NO_MITSHM=1
    volumes:
      - /home/riteshm03/Downloads/Zed/:/tmp/darknet/zed-python-api/pyzed/zed_pycharm
      - /tmp/.X11-unix:/tmp/.X11-unix/




